### ISSUE TITLE
steps not working

### ISSUE THREAD

**Issue by shubhnsoni** [isaiahbjork/Auto-GPT-MetaTrader-Plugin#3]
Welcome to Auto-GPT!  run with '--help' for more information.
Create an AI-Assistant:  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: TradeGPT
TradeGPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
TradeGPT is: fetch candlestick data
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: fetch candlestick data for the 1 hour chart on EURUSD
Goal 2: Terminate
Goal 3: 
Using memory of type:  LocalCache
Using Browser:  chrome
 THOUGHTS:  I will fetch candlestick data for the 1 hour chart on EURUSD. I can use the Alpha Vantage API to get this data.
REASONING:  I have used the Alpha Vantage API before to fetch financial data, and it is a reliable source for this type of data.
PLAN: 
-  Use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD.
CRITICISM:  I need to ensure that I am using the correct API key and that the data is being fetched correctly.
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command do_nothing returned: No action performed.
 THOUGHTS:  I will use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD. I need to ensure that I have the correct API key and that the data is being fetched correctly.
REASONING:  I have used the Alpha Vantage API before to fetch financial data, and it is a reliable source for this type of data. I need to ensure that I have the correct API key and that the data is being fetched correctly to avoid any errors.
PLAN: 
-  Check that I have the correct API key for Alpha Vantage.
-  Use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD.
CRITICISM:  I need to ensure that I am using the correct API key and that the data is being fetched correctly.
NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:

**Comment by isaiahbjork** [comment]
> Welcome to Auto-GPT! run with '--help' for more information. Create an AI-Assistant: Enter the name of your AI and its role below. Entering nothing will load defaults. Name your AI: For example, 'Entrepreneur-GPT' AI Name: TradeGPT TradeGPT here! I am at your service. Describe your AI's role: For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.' TradeGPT is: fetch candlestick data Enter up to 5 goals for your AI: For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously' Enter nothing to load defaults, enter nothing when finished. Goal 1: fetch candlestick data for the 1 hour chart on EURUSD Goal 2: Terminate Goal 3: Using memory of type: LocalCache Using Browser: chrome THOUGHTS: I will fetch candlestick data for the 1 hour chart on EURUSD. I can use the Alpha Vantage API to get this data. REASONING: I have used the Alpha Vantage API before to fetch financial data, and it is a reliable source for this type of data. PLAN:
> 
> * Use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD.
>   CRITICISM:  I need to ensure that I am using the correct API key and that the data is being fetched correctly.
>   NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
>   Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
>   Input:y
>   -=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
>   SYSTEM:  Command do_nothing returned: No action performed.
>   THOUGHTS:  I will use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD. I need to ensure that I have the correct API key and that the data is being fetched correctly.
>   REASONING:  I have used the Alpha Vantage API before to fetch financial data, and it is a reliable source for this type of data. I need to ensure that I have the correct API key and that the data is being fetched correctly to avoid any errors.
>   PLAN:
> * Check that I have the correct API key for Alpha Vantage.
> * Use the Alpha Vantage API to fetch candlestick data for the 1 hour chart on EURUSD.
>   CRITICISM:  I need to ensure that I am using the correct API key and that the data is being fetched correctly.
>   NEXT ACTION:  COMMAND = do_nothing ARGUMENTS = {}
>   Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
>   Input:

Sometimes it doesn't recognize the commands it has so just give it human input to use the command and it should use it.
