### ISSUE TITLE
Error fetching candlestick data for GBPUSD pair in TraderGPT

### ISSUE THREAD

**Issue by mo-bay** [isaiahbjork/Auto-GPT-MetaTrader-Plugin#4]
**Description:**
I encountered an error while trying to fetch candlestick data for the GBPUSD pair using the TraderGPT, an AI-powered trader that performs technical analysis. The error seems to be related to the connection to the API.

**Details:**
- TraderGPT Role: AI-powered trader that enters trades after doing technical analysis
- Goal: Fetch candlestick data for GBPUSD pair
- Memory Type: PineconeMemory
- Browser: Chrome

**Error Message:**
`Error: HTTPSConnectionPool(host='mt-market-data-client-api-v1.new-york.agiliumtrade.ai', port=443): Max retries exceeded with url: /users/current/accounts/45826ed7-e48f-4d9f-941f-41e7a3d71310/historical-market-data/symbols/GBPUSD/timeframes/1h/candles?limit=15 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1277f4b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))`

**Steps to reproduce:**
1. Use the 'fetch_candlesticks' command to retrieve the data for the GBPUSD pair with the following arguments: {'symbol': 'GBPUSD', 'timeframe': '1h'}.
2. Authorize the command.
3. Observe the error message.

**Expected behavior:**
The 'fetch_candlesticks' command should successfully retrieve the candlestick data for the GBPUSD pair without any errors.

**Additional context:**
Please let me know if any additional information is required to diagnose or resolve this issue. Thank you!

**Comment by mo-bay** [comment]
`        url = f"https://mt-market-data-client-api-v1.new-york.agiliumtrade.ai/users/current/accounts/{account_id}/historical-market-data/symbols/{symbol}/timeframes/{timeframe}/candles?limit=15"
`

Ok figured out that the my api access was for london and in the code it connects to newyork 

Problem solved i guess

**Comment by mo-bay** [comment]
p.s. it seems that the newyork api is facing outages

**Comment by isaiahbjork** [comment]
> p.s. it seems that the newyork api is facing outages, i edited the code and replaced all api endpoint to london in personal repo

I will make changes for you to set your own region in the .env

**Comment by GameWorldsNFT** [comment]
you have to have metatrader open and then i had to also tell my agent/ AutoGPt that i had metatrader open and the internet was ok. after i did that everything started working
