### ISSUE TITLE
SYSTEM:  Command fetch_candlesticks returned: Failed to get candlesticks

### ISSUE THREAD

**Issue by Rmeulstee** [isaiahbjork/Auto-GPT-MetaTrader-Plugin#8]
Error after using the test commands:
![image](https://user-images.githubusercontent.com/132207807/235434898-a24019c7-289e-4d0a-a54f-2574d60171a9.png)

It does pull account information, so only the Market data is not working: 
![image](https://user-images.githubusercontent.com/132207807/235435524-6731e55c-ae16-4ffc-b9ed-9a3abc190480.png)

**Comment by GameWorldsNFT** [comment]
you have to have metatrader open and then i had to also tell my agent/ AutoGPt that i had metatrader open and the internet was ok. after i did that everything started working

**Comment by harryjmg** [comment]
Same problem here. Any ideas ?

**Comment by harryjmg** [comment]
I run just a part of the code for debugging purpose, here is the response returned by Meta API : 
```python3 auto_gpt_workspace/get_market_datas.py
Fetching candlesticks...
Timeframe matched!
full response:  {'id': 970, 'error': 'ValidationError', 'message': 'Candle historical market data is not supported for MT5 G2 accounts'}```

This is clear : **Candle historical market data is not supported for MT5 G2 accounts**

This is said here on Meta API also : https://metaapi.cloud/docs/client/
"historical market data is available for G1 and MT4 G2 only"

I created an MT4 account and it works like a charm 🎉

I hope it will help others :)

**Comment by Cruentus1978** [comment]
> I run just a part of the code for debugging purpose, here is the response returned by Meta API :
> 
> ```
> python3 auto_gpt_workspace/get_market_datas.py
> Fetching candlesticks...
> Timeframe matched!
> full response:  {'id': 970, 'error': 'ValidationError', 'message': 'Candle historical market data is not supported for MT5 G2 accounts'}
> ```
> 
> This is clear : **Candle historical market data is not supported for MT5 G2 accounts**
> 
> The info can also be found on the meta docs : https://metaapi.cloud/docs/client/
> 
> > _"historical market data is available for G1 and MT4 G2 only"_
> 
> I created an MT4 account and it works like a charm 🎉
> 
> I hope it will help others :)

I keep getting this message: "Error: The following AI output couldn't be converted to a JSON:" and notes about how it cant fetch candlesticks. I changed my MetaAPI region to New-York from london on the env., but I feel like there is something I am missing. If you got yours working, I would appreciate some help. Thanks in advance.
